# Generated by Django 3.0.5 on 2020-04-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('recordnum', models.AutoField(primary_key=True, serialize=False)),
                ('onhand', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lineitem',
            fields=[
                ('linekey', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('lineid', models.IntegerField(db_column='lineID')),
                ('cost', models.FloatField(blank=True, db_column='Cost', null=True)),
            ],
            options={
                'db_table': 'lineitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Masterinvoice',
            fields=[
                ('invoiceid', models.CharField(db_column='invoiceID', max_length=48, primary_key=True, serialize=False)),
                ('datesent', models.DateField()),
                ('paymentduedate', models.DateField()),
                ('grossamount', models.FloatField()),
            ],
            options={
                'db_table': 'masterinvoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Masteritem',
            fields=[
                ('itemid', models.CharField(db_column='itemID', max_length=48, primary_key=True, serialize=False)),
                ('lastpricechange', models.DateField(blank=True, db_column='lastPriceChange', null=True)),
                ('previouscost', models.FloatField(blank=True, db_column='previousCost', null=True)),
                ('cost', models.FloatField()),
                ('intialpurchasedate', models.DateField(blank=True, db_column='intialPurchaseDate', null=True)),
            ],
            options={
                'db_table': 'masteritem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mastervendor',
            fields=[
                ('vendorid', models.CharField(db_column='vendorId', max_length=48, primary_key=True, serialize=False)),
                ('contactname', models.CharField(blank=True, db_column='contactName', max_length=50, null=True)),
                ('vendorname', models.CharField(db_column='vendorName', max_length=48)),
                ('country', models.CharField(blank=True, max_length=48, null=True)),
                ('state', models.CharField(blank=True, max_length=48, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'mastervendor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderheader',
            fields=[
                ('orderreceived', models.DateField(blank=True, null=True)),
                ('orderdate', models.DateField()),
                ('orderid', models.AutoField(db_column='orderID', primary_key=True, serialize=False)),
                ('shipdate', models.DateField(blank=True, null=True)),
                ('cost', models.FloatField()),
            ],
            options={
                'db_table': 'orderheader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Termscodes',
            fields=[
                ('termsid', models.CharField(db_column='termsID', max_length=12, primary_key=True, serialize=False)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('daystoearndiscount', models.IntegerField(blank=True, db_column='daysToEarnDiscount', null=True)),
            ],
            options={
                'db_table': 'termscodes',
                'managed': False,
            },
        ),
    ]
